data = [
    {"name": "Shah Rukh Khan", "description": "Bollywood actor", "followers": 47000000},
    {"name": "Deepika Padukone", "description": "Bollywood actress", "followers": 80000000},
    {"name": "Alia Bhatt", "description": "Bollywood actress", "followers": 87000000},
    {"name": "Ranveer Singh", "description": "Bollywood actor", "followers": 47000000},
    {"name": "Priyanka Chopra", "description": "Actress and global icon", "followers": 92000000},
    {"name": "Katrina Kaif", "description": "Bollywood actress", "followers": 81000000},
    {"name": "Salman Khan", "description": "Bollywood actor", "followers": 70000000},
    {"name": "Amitabh Bachchan", "description": "Veteran Bollywood actor", "followers": 38000000},
    {"name": "Anushka Sharma", "description": "Bollywood actress", "followers": 69000000},
    {"name": "Varun Dhawan", "description": "Bollywood actor", "followers": 47000000},
    {"name": "Kriti Sanon", "description": "Bollywood actress", "followers": 58000000},
    {"name": "Kiara Advani", "description": "Bollywood actress", "followers": 36000000},
    {"name": "Vicky Kaushal", "description": "Bollywood actor", "followers": 22000000},
    {"name": "Shraddha Kapoor", "description": "Bollywood actress", "followers": 95000000},
    {"name": "Akshay Kumar", "description": "Bollywood actor", "followers": 67000000},
    {"name": "Aamir Khan", "description": "Bollywood actor", "followers": 12000000},
    {"name": "Karan Johar", "description": "Film director", "followers": 18000000},
    {"name": "Rashmika Mandanna", "description": "Actress", "followers": 46000000},
    {"name": "Sidharth Malhotra", "description": "Bollywood actor", "followers": 35000000},
    {"name": "Janhvi Kapoor", "description": "Bollywood actress", "followers": 26000000},
    {"name": "Virat Kohli", "description": "Indian cricketer", "followers": 270000000},
    {"name": "MS Dhoni", "description": "Indian cricketer", "followers": 50000000},
    {"name": "Neeraj Chopra", "description": "Olympic gold medalist", "followers": 12000000},
    {"name": "CarryMinati", "description": "YouTuber", "followers": 21000000},
    {"name": "Bhuvan Bam", "description": "YouTuber", "followers": 18000000},
    {"name": "Narendra Modi", "description": "Prime Minister of India", "followers": 100000000},
    ]